# Implement dev container w/ deps, tooling, scripts, aliases etc for terraform
# alias terraform='docker run --rm -it -w $PWD:$PWD -v $PWD:$PWD terraform:someversion'
# commands for init, plan and apply

# advantages
# - never install a tool again
# - allows you to switch versions easily and rapidly
# - if it works on your machine it'll work on the server / in the pipeline
