---
- name: Update packages
  hosts: all # "{{ hosts }}"
  become: true
  tasks:
    - name: Upgrade apt packages
      become: true
      ansible.builtin.apt:
        upgrade: true
        update_cache: true

    - name: Check if system reboot is required
      become: true
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required

    # - name: Send Discord message
    #   uri:
    #     url: "{{ discord_webhook_url }}"
    #     method: POST
    #     body_format: json
    #     body: '{"content": "Reboot required on {{ inventory_hostname }}"}'
    #     headers:
    #       Content-Type: application/json
    #     status_code: 204
    #   when: reboot_required.stat.exists
