return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "comment",
      "csv",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "html",
      "javascript",
      "jq",
      "json",
      "kconfig",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "sql",
      "ssh_config",
      "terraform",
      "toml",
      "nix",
      "tsx",
      "typescript",
      "vim",
      "vue",
      "xml",
      "yaml",
    },
  },
}
