---
- name: Bluetooth | Install bluetooh packages
  package:
    state: present
    name:
      - bluez
      - bluez-utils
      - bluez-libs
      - blueman
  become: true
  tags:
    - bluetooth
    - packages

- name: bluetooth | Enable bluetooth service
  service:
    name: bluetooth.service
    enabled: yes
    state: started
  notify:
    - reload systemd config
  tags:
    - bluetooth
    - systemd
