---
- name: Docker | Install package
  package:
    name: docker
    state: present
  tags:
    - docker
    - packages

- name: Docker | Add user to docker group
  user:
    name: "{{ user.name }}"
    groups: docker
    append: true
  tags:
    - docker

- name: Docker | Enable docker service
  service:
    name: docker.service
    enabled: yes
    state: started
  tags:
    - docker
