---
- name: git | Install git
  community.general.homebrew:
    state: present
    name:
      - git
  tags:
    - git
    - packages

- name: Git | Install git config
  ansible.builtin.template:
    src: "{{ user.home }}/dotfiles/templates/gitconfig.j2"
    dest: "{{ user.home }}/.gitconfig"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0700"
  tags:
    - git
