---
- name: libinput | Install packages
  package:
    state: present
    name:
      - libinput
      - xdotool
      - xf86-input-libinput
  become: true
  tags:
    - input
    - packages

- name: libinput | Install libinput-gestures
  yay:
    name:
      - libinput-gestures
    state: present
  tags:
    - input
    - packages

- name: libinput | Install libinput-gestures.conf
  copy:
    src: files/libinput-gestures.conf
    dest: '{{ user.config }}/libinput-gestures.conf'
  notify:
    - ensure folders
  tags:
    - input

- name: libinput | Install libinput-gestures.desktop
  copy:
    src: files/libinput-gestures.desktop
    dest: '{{ user.config }}/autostart/libinput-gestures.desktop'
  notify:
    - ensure folders
  tags:
    - input
