---
- name: lockscreen | Install lockscreen packages
  package:
    name:
      - imagemagick
      - feh
      - xorg-xrandr
      - xorg-xdpyinfo
      - i3lock-color
    state: present
  become: true
  tags:
    - lockscreen
    - packages

- name: lockscreen | Install betterlockscreen (AUR)
  yay:
    name:
      - betterlockscreen
    state: present
  tags:
    - lockscreen
    - packages

- name: lockscreen | Install betterlockscreen config
  copy:
    src: files/betterlockscreenrc
    dest: '{{ user.config }}/betterlockscreenrc'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
  notify:
    - ensure folders
  tags:
    - lockscreen

- name: lockscreen | Update betterlockscreen cache with image
  command: 'betterlockscreen -u {{ user.config }}/wall.png'
  tags:
    - lockscreen

- name: lockscreen | Enable lockscreen on suspend
  become: true
  systemd:
    enabled: true
    name: 'betterlockscreen@{{ user.name }}'
    daemon-reload: true
  tags:
    - lockscreen
    - systemd
