---
- name: nvim | Install neovim packages
  package:
    state: present
    name:
      - xsel
      - xclip
      - ctags
      - neovim
      - nodejs
      - npm
      - python-neovim
      - prettier
      - libnghttp2
  become: true
  tags:
    - neovim
    - packages

- name: nvim | Install nvim node
  shell: npm install -g neovim
  tags:
    - neovim

- name: nvim | Clone dotfiles from github
  become_user: '{{ user.name }}'
  git:
    repo: https://github.com/dsnn/dotfiles.git
    dest: '{{ user.home }}/projects/dotfiles'
    version: master
    update: yes
  notify:
    - ensure folders
  tags:
    - neovim

- name: nvim | Create symbolic link
  file:
    src: '{{ user.home }}/projects/dotfiles/files/vim'
    dest: '{{ user.config }}/nvim'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    state: link
    follow: false
  notify:
    - ensure folders
  tags:
    - neovim
