---
- name: network | Install network packages
  package:
    name:
      - networkmanager
      - network-manager-applet
      - dhclient
    state: present
  become: true
  tags:
    - network
    - packages

- name: network | Enable network manager service
  become: true
  systemd:
    enabled: true
    name: '{{ item }}'
    daemon-reload: true
    state: started
  with_items:
    - NetworkManager.service
  tags:
    - network
    - systemd
