---
- name: paccache | Install pacman cache cleanup service
  copy:
    src: files/paccache.service
    dest: /etc/systemd/system/paccache.service
  notify:
    - reload systemd config
  tags:
    - paccache
    - pacman
    - systemd

- name: paccache | Enable pacman cache cleanup service
  service:
    name: paccache.service
    enabled: yes
    state: started
  notify:
    - reload systemd config
  tags:
    - paccache
    - pacman
    - systemd

- name: paccache | Install pacman cache cleanup timer
  copy:
    src: files/paccache.timer
    dest: /etc/systemd/system/paccache.timer
  notify:
    - reload systemd config
    - restart paccache
  tags:
    - paccache
    - pacman
    - systemd

- name: paccache | Enable and start pacman cache cleanup timer
  service:
    name: paccache.timer
    enabled: yes
    state: started
  tags:
    - paccache
    - pacman
    - systemd
