---
- name: power | Install user battery service
  template:
    src: templates/check-battery.service.j2
    dest: '{{ user.config }}/systemd/user/check-battery.service'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
  notify:
    - reload systemd config
    - ensure folders
  tags:
    - power
    - battery
    - systemd

- name: power | Install user battery timer
  become: true
  copy:
    src: files/check-battery.timer
    dest: '{{ user.config }}/systemd/user/check-battery.timer'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
  notify:
    - reload systemd config
    - restart check battery
  tags:
    - power
    - battery
    - systemd

- name: power | Enable user battery timer
  become: true
  become_user: '{{ user.name }}'
  service:
    name: check-battery.timer
    enabled: yes
    state: started
    scope: user
  notify:
    - reload systemd config
  tags:
    - power
    - battery
    - systemd

- name: power | Install power packages
  package:
    state: present
    name:
      - tlp
      - tlp-rdw
      - acpi
      - acpi_call
      - tp_smapi
      - powertop
  become: true
  tags:
    - power
    - packages

- name: power | Configure TLP
  copy:
    src: files/tlp
    dest: /etc/default/tlp
  become: true
  tags:
    - power
    - tlp

- name: power | Enable TLP
  service:
    name: tlp
    enabled: yes
    state: started
  become: true
  tags:
    - power
    - tlp

- name: power | Enable TLP Sleep
  service:
    name: tlp-sleep
    enabled: yes
    state: started
    daemon-reload: yes
  become: true
  tags:
    - power
    - tlp

- name: power | Enable NetworkManager dispatcher
  service:
    name: NetworkManager-dispatcher
    enabled: yes
  become: true
  tags:
    - power
    - tlp

- name: power | Mask systemd-rfkill service
  systemd:
    name: systemd-rfkill
    masked: yes

- name: power | Mask systemd-rfkill socket
  systemd:
    name: systemd-rfkill.socket
    masked: yes

- name: power | Install powertop service
  become: true
  copy:
    src: files/powertop.service
    dest: /etc/systemd/system/powertop.service
  tags:
    - power
    - powertop
