# vim:ft=yaml.ansible:
---
- name: Time | Set timezone to Europe/Stockholm
  become: true
  timezone:
    name: Europe/Stockholm
  tags:
    - time

- name: Time | Check timedatectl NTP status
  command: timedatectl status
  register: timedatectl_ntp_status
  changed_when: false
  tags:
    - time

- name: Time | Enable timedatectl NTP
  command: timedatectl set-ntp true
  become: true
  when: "'System clock synchronized: no' in timedatectl_ntp_status"
  tags:
    - time
