---
- name: Tmux | Install tmuxp
  ansible.builtin.package:
    state: present
    name:
      - tmuxp

- name: Tmux | Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ user.home }}/.config/tmux"
    - "{{ user.home }}//.config/tmux/resurrect"

- name: Tmux | Symlink config
  ansible.builtin.file:
    src: "{{ user.home }}/dotfiles/files/tmux.conf"
    dest: "{{ user.home }}/.config/tmux/tmux.conf"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link
    follow: false

- name: Tmux | Clone tmux plugins from github
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/{{ item }}
    dest: "{{ user.home }}/.config/tmux/plugins/{{ item }}"
    version: master
    update: false
  with_items:
    - tpm
    - tmux-continuum
    - tmux-resurrect
  tags:
    - tmux
    - packages

- name: Tmux | Update plugins owner
  ansible.builtin.file:
    path: "{{ user.home}}/.config/tmux/plugins"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    recurse: true

- name: Tmux | Symlink tmuxp workspaces
  ansible.builtin.file:
    src: "{{ user.home }}/dotfiles/files/tmuxp"
    dest: "{{ user.home }}/.config/tmuxp"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link
