---
- name: tmux | Install packages
  package:
    name:
      - tmux
    state: present
  tags:
    - tmux
    - packages

- name: tmux | Install tmux config
  copy:
    src: files/tmux
    dest: '{{ user.home }}/.tmux.conf'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
  tags:
    - tmux

- name: tmux | Clone tmux plugins from github
  become_user: '{{ user.name }}'
  git:
    repo: https://github.com/tmux-plugins/{{ item }}
    dest: '{{ user.home }}/.tmux/plugins/{{ item }}'
    version: master
    update: yes
  with_items:
    - tpm
    - tmux-continuum
    - tmux-sensible
    - tmux-pain-control
    - tmux-yank
    - tmux-prefix-highlight
  tags:
    - tmux
    - packages
