---
- name: Tmux | Install package
  package:
    state: present
    name: 
      - tmux
      - tmuxp

- name: Tmux | Symlink config
  file: 
    src: "{{ user.home }}/dotfiles/files/tmux.conf"
    dest: "{{ user.home }}/.config/tmux/tmux.conf" 
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link

- name: tmux | Clone tmux plugins from github
  git:
    repo: https://github.com/tmux-plugins/{{ item }}
    dest: '{{ user.home }}/.config/tmux/plugins/{{ item }}'
    version: master
    update: no 
  with_items:
    - tpm
    - tmux-continuum
    - tmux-resurrect
  tags:
    - tmux
    - packages

- name: Tmux | Symlink tmuxp workspaces
  file: 
    src: "{{ user.home }}/dotfiles/files/tmuxp"
    dest: "{{ user.home }}/.config/tmuxp" 
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link
