---
- name: user | Check if user exists
  command: 'getent passwd {{ user.name }}'
  register: check_if_user_exists
  ignore_errors: true
  changed_when: false
  tags:
    - user

- name: user | Prompt for user password to create
  pause:
    prompt: 'Enter desired user password'
    echo: false
  when: check_if_user_exists is failed
  register: user_password
  no_log: true
  tags:
    - user

- name: user | Create user group
  group:
    name: '{{ user.group }}'
    state: present
  tags:
    - user

- name: user | Create user
  become: true
  user:
    name: '{{ user.name }}'
    group: '{{ user.group }}'
    groups:
      - '{{ user.group }}'
      - input
      - wheel
    password: "{{ user_password.user_input | default('password') | password_hash('sha512') }}"
    shell: '{{ user.shell }}'
    update_password: on_create
    append: true
  tags:
    - user
