---
- name: wallpaper | Install wallpaper
  copy:
    src: files/wall.png
    dest: '{{ user.config }}/wall.png'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
  notify:
    - ensure folders
  tags:
    - wallpaper
