---
- name: Xorg | Install xorg packages
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xmodmap
      - xorg-xdpyinfo
      - xorg-xev
      - xorg-sessreg
      - xautomation
      - xorg-xauth
      - xf86-video-intel
      - mesa
      - xf86-input-libinput
      - xf86-input-mouse
      - xf86-input-keyboard
      - xorg-xmodmap
      - xorg-xrdb
      - xorg-xbacklight
      - xorg-xgamma
      - xorg-xinput
      - xorg-xrandr
      - xorg-xset
      - xorg-server
      - xdotool
      - xwallpaper
    state: present
  tags:
    - xorg
    - packages

- name: Xorg | Install xinit config
  copy:
    src: xinitrc
    dest: '{{ user.home }}/.xinitrc'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
  tags:
    - xorg

- name: Xorg | Install xresources
  copy:
    src: xresources
    dest: '{{ user.home }}/.Xresources'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
  tags:
    - xorg

- name: Add user to video group
  user:
    name: '{{ user.name }}'
    groups: video
    append: yes
  tags:
    - xorg
    - user
