---
- name: aur | Create aur build user
  user:
    name: '{{ aur.user }}'
    group: '{{ aur.group }}'
    password: "{{ aur.password | default('password') | password_hash('sha512') }}"
    append: yes
  tags:
    - aur
    - packages

- name: aur | Set aur builder passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: 'aur_builder ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
  tags:
    - aur

- name: aur | Clone yay from github
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /tmp/yay
    version: master
    update: yes
  tags:
    - aur
    - packages

- name: aur | Change yay folder owner
  file:
    path: /tmp/yay
    owner: '{{ aur.user }}'
    group: '{{ aur.group }}'
    recurse: yes
  tags:
    - aur
    - packages

- name: aur | Remove sudo lecture
  file:
    path: /var/db/sudo/lectured/aur_builder
    state: touch
  tags:
    - aur
    - packages

- name: aur | Make and install yay
  become: yes
  become_user: '{{ aur.user }}'
  command: makepkg --noconfirm -si
  args:
    chdir: /tmp/yay
    creates: /usr/bin/yay
  tags:
    - aur
    - packages
