---
- name: ZSH | Install package and dependencies
  pacman:
    state: present
    name:
      - zsh
      - zsh-completions
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - powerline
      - powerline-fonts
  become: true
  tags:
    - zsh
    - packages

- name: ZSH | Install zshrc config
  copy:
    src: files/zsh/zshrc
    dest: '{{ user.home }}/.zshrc'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
  tags:
    - zsh

- name: ZSH | Install aliases
  copy:
    src: files/zsh/aliases
    dest: '{{ user.home }}/.aliases'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
  tags:
    - zsh
    - aliases

- name: ZSH | Install exports
  copy:
    src: files/zsh/exports
    dest: '{{ user.home }}/.exports'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
  tags:
    - zsh

- name: ZSH | Install dircolors config
  copy:
    src: dircolors
    dest: '{{ user.config }}/dircolors'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
  tags:
    - zsh
