---
- name: ZSH | Copy zshenv 
  copy:
    src: "{{ user.home }}/dotfiles/files/zshenv"
    dest: "{{ user.home }}/.zshenv"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: ZSH | Install package(s)
  package:
    state: present
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions

- name: ZSH | Symlink config (zshrc)
  file: 
    src: "{{ user.home }}/dotfiles/files/zsh"
    dest: "{{ user.home }}/.config/zsh"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link

- name: ZSH | Create secrets dir
  file:
    path: "{{ user.home }}/.secrets"
    state: directory
    mode: '0755'

- name: ZSH | Create secret exports from template
  template:
    src: "{{ user.home }}/dotfiles/templates/exports.secret.j2"
    dest: "{{ user.home }}/.secrets/exports.secret"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"

- name: ZSH | Symlink startship prompt config
  file:
    src: "{{ user.home }}/dotfiles/files/starship.toml"
    dest: "{{ user.home }}/.config/starship.toml"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link

- name: ZSH | Install dircolors config
  file:
    src: "{{ user.home }}/dotfiles/files/dircolors"
    dest: "{{ user.home }}/.config/dircolors"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link
  tags:
    - zsh
