---
- name: ZSH | Copy zshenv
  ansible.builtin.copy:
    src: "{{ user.home }}/dotfiles/files/zshenv"
    dest: "{{ user.home }}/.zshenv"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0700"

- name: ZSH | Install package(s)
  ansible.builtin.package:
    state: present
    name:
      - zsh
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - keychain

- name: ZSH | Symlink config (zshrc)
  ansible.builtin.file:
    src: "{{ user.home }}/dotfiles/files/zsh"
    dest: "{{ user.home }}/.config/zsh"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link

- name: ZSH | Create secrets dir
  ansible.builtin.file:
    path: "{{ user.home }}/.secrets"
    state: directory
    mode: "0700"

- name: ZSH | Create secret exports from template
  ansible.builtin.template:
    src: "{{ user.home }}/dotfiles/templates/exports.secret.j2"
    dest: "{{ user.home }}/.secrets/exports.secret"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0700"

- name: ZSH | Symlink startship prompt config
  ansible.builtin.file:
    src: "{{ user.home }}/dotfiles/files/starship.toml"
    dest: "{{ user.home }}/.config/starship.toml"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link

- name: ZSH | Install dircolors config
  ansible.builtin.file:
    src: "{{ user.home }}/dotfiles/files/dircolors"
    dest: "{{ user.home }}/.config/dircolors"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link
  tags:
    - zsh

- name: ZSH | Change user shell to zsh
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: /usr/bin/zsh
  tags:
    - zsh
