---
- name: ZSH | Create zsh profile
  ansible.builtin.template:
    src: "{{ user.home }}/dotfiles/templates/zprofile.j2"
    dest: "{{ user.home }}/.config/zsh/.zprofile"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0755"
  tags:
    - zsh
    - zprofile

- name: ZSH | Copy zshenv
  ansible.builtin.copy:
    src: "{{ user.home }}/dotfiles/files/zshenv"
    dest: "{{ user.home }}/.zshenv"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0700"
  tags:
    - zsh

# - name: ZSH | Install package(s)
#   community.general.homebrew:
#     state: present
#     name:
#       - zsh
#       - zsh-autosuggestions
#       - zsh-completions
#       - zsh-syntax-highlighting
#   tags:
#     - zsh

- name: ZSH | Create .config directory if it does not exist
  ansible.builtin.file:
    path: "{{ user.home }}/.config"
    state: directory
    mode: "0755"

- name: ZSH | Symlink config (zshrc)
  ansible.builtin.file:
    src: "{{ user.home }}/dotfiles/files/zsh"
    dest: "{{ user.home }}/.config/zsh"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link
  tags:
    - zsh

- name: ZSH | Create secrets dir
  ansible.builtin.file:
    path: "{{ user.home }}/.secrets"
    state: directory
    mode: "0700"
  tags:
    - zsh

- name: ZSH | Create secret exports from template
  ansible.builtin.template:
    src: "{{ user.home }}/dotfiles/templates/exports.secret.j2"
    dest: "{{ user.home }}/.secrets/exports.secret"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    mode: "0700"
  tags:
    - zsh

- name: ZSH | Symlink startship prompt config
  ansible.builtin.file:
    src: "{{ user.home }}/dotfiles/files/starship"
    dest: "{{ user.home }}/.config/starship"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link
  tags:
    - zsh

- name: ZSH | Install dircolors config
  ansible.builtin.file:
    src: "{{ user.home }}/dotfiles/files/dircolors"
    dest: "{{ user.home }}/.config/dircolors"
    owner: "{{ user.name }}"
    group: "{{ user.group }}"
    state: link
  tags:
    - zsh
# TODO: workaround for using brew installed shell
# - name: ZSH | Change user shell to zsh
#   ansible.builtin.command:
#     cmd: command -v zsh | sudo tee -a /etc/shells
#   tags:
#    - zsh
#    - shell
#
# - name: ZSH | Change user shell to zsh
#   ansible.builtin.command:
#     cmd: sudo chsh -s "$(command -v zsh)" "${USER}"
#   tags:
#    - zsh
#    - shell

# - name: ZSH | Change user shell to zsh
#   become: true
#   ansible.builtin.user:
#     name: "{{ user.name }}"
#     shell: /home/linuxbrew/.linuxbrew/bin/zsh
#   tags:
#    - zsh
#    - shell
