---
- name: Install Traefik
  hosts: docker
  tasks:
    - name: Copy docker-compose file
      ansible.builtin.copy:
        src: "{{ local_docker_dir }}/traefik/docker-compose.yaml"
        dest: "{{ remote_docker_dir }}/traefik/"
        mode: u=rw,g=r,o=r

    - name: Copy .env file
      ansible.builtin.copy:
        src: "{{ local_docker_dir }}/traefik/.env"
        dest: "{{ remote_docker_dir }}/traefik/"
        mode: u=rw,g=rwx,o=rwx

    - name: Create traefik config dir
      ansible.builtin.file:
        path: "{{ remote_docker_dir }}/traefik/config"
        state: directory

    - name: Copy traefik configuration
      ansible.builtin.copy:
        src: "{{ local_docker_dir }}/traefik/config/traefik.yml"
        dest: "{{ remote_docker_dir }}/traefik/config/traefik.yml"
        force: true # replace content if src differ

    - name: Create traefik acme.json (if it doesnt exists)
      become: true
      ansible.builtin.file:
        path: "{{ remote_docker_dir }}/traefik/config/acme.json"
        state: touch
        mode: u+rw,g-rwx,o-rwx
        modification_time: preserve
        access_time: preserve

    - name: Create traefik network
      community.docker.docker_network:
        name: traefik-network

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: "{{ remote_docker_dir }}/traefik"
        recreate: always
      register: output
