---
- name: Install Traefik
  hosts: docker
  tasks:
    - name: Copy docker-compose file
      ansible.builtin.copy:
        src: "{{ local_docker_dir }}/traefik/docker-compose.yaml"
        dest: "{{ remote_docker_dir }}/traefik/"

    - name: Copy env file
      ansible.builtin.copy:
        src: "{{ local_docker_dir }}/traefik/.env"
        dest: "{{ remote_docker_dir }}/traefik/"

    - name: Copy configuration
      ansible.builtin.copy:
        src: "{{ local_docker_dir }}/traefik/config"
        dest: "{{ remote_docker_dir }}/traefik"
        force: true # replace content if src differ

    - name: Create cert dir
      ansible.builtin.file:
        path: "{{ remote_docker_dir }}/traefik/data/certs"
        state: directory

    - name: Create traefik network
      docker_network:
        name: traefik-network

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: "{{ remote_docker_dir }}/traefik"
        recreate: always
      register: output
