---
services:
  traefik:
    image: docker.io/library/traefik:v3.1.6
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./config/conf/:/etc/traefik/conf/:ro
      - ./data/certs/:/var/traefik/certs/:rw
    networks:
      - traefik-network
    environment:
      - CF_API_EMAIL=${EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    command:
      - "--certificatesresolvers.cloudflare.acme.email=${EMAIL}"
    restart: unless-stopped

networks:
  traefik-network:
    external: true
