---
- name: Docker | Install package
  ansible.builtin.package:
    name: docker
    state: present
  tags:
    - docker
    - packages

- name: Docker | Add user to docker group
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: docker
    append: true
  tags:
    - docker

- name: Docker | Enable docker service
  ansible.builtin.service:
    name: docker.service
    enabled: true
    state: started
  tags:
    - docker
