require('plugins')
require('dsn.globals')
require('dsn.treesitter')
require('dsn.nvimtree')
require('dsn.statusline')
require('dsn.bufferline')
require('dsn.prettier')
require('dsn.lsp')
require('dsn.completion')
require('dsn.stylua')
-- require('dsn.comment')
require('dsn.signs')
require('dsn.settings')
require('dsn.mappings')
