vim.bo.autoindent = true
vim.bo.expandtab = true
vim.bo.shiftwidth = 4
vim.bo.smartindent = true
vim.bo.softtabstop = 4
vim.bo.tabstop = 4
vim.bo.textwidth = 120
vim.bo.wrapmargin = 8
vim.cmd('set cpoptions+=$')
vim.cmd('set iskeyword+=-')
vim.cmd('set shortmess+=c')
vim.cmd('set showbreak=_')
vim.cmd('set tags=./tags;,tags;')
vim.cmd('set whichwrap+=<,>,[,],h,l')
vim.o.backup = false
vim.o.clipboard = "unnamedplus"
vim.o.cmdheight = 2
vim.o.conceallevel = 0
vim.o.fileencoding = "utf-8"
vim.o.hidden = true
vim.o.history = 1000
vim.o.ignorecase = true
vim.o.inccommand = 'nosplit'
vim.o.mouse = "a"
vim.o.pumheight = 10
vim.o.scrolloff = 10
vim.o.shiftround = true
vim.o.showmatch = true
vim.o.showmode = false
vim.o.showtabline = 2
vim.o.smartcase = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.swapfile = false
vim.o.syntax = 'on'
vim.o.t_Co = "256"
vim.o.termguicolors = true
vim.o.timeoutlen = 300
vim.o.updatetime = 300
vim.o.writebackup = false
vim.wo.cursorline = true
vim.wo.foldenable = false
vim.wo.foldlevel = 1
vim.wo.foldmethod = "syntax"
vim.wo.foldnestmax = 10
vim.wo.linebreak = true
vim.wo.number = true
vim.wo.relativenumber = true
vim.wo.signcolumn ="yes"
vim.wo.wrap = true
vim.o.bg = "dark"

vim.cmd("colorscheme aurora")
