typeset -U path cdpath fpath manpath

fpath=(~/.config/zsh/completions $fpath)
autoload -Uz compinit
compinit

source_if_exists() {
  [[ -r "$1" ]] && source "$1"
}

# ---------------------- #
#         plugins        #
# ---------------------- #

# Arch paths
source_if_exists /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source_if_exists /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source_if_exists /usr/share/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh

# Debian/Ubuntu-ish paths
source_if_exists /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source_if_exists /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source_if_exists "$HOME/.local/share/zsh/plugins/fzf-tab/fzf-tab.plugin.zsh"

ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd completion history)

# ---------------------- #
#         core           #
# ---------------------- #

HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="/home/dsn/.config/zsh/history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_SAVE_NO_DUPS
unsetopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt autocd

# make vi mode transitions faster
export KEYTIMEOUT=1

# vi mode
bindkey -v

# ---------------------- #
#         fzf            #
# ---------------------- #

if [[ $options[zle] = on ]]; then
  source <(fzf --zsh)
fi

# Arch paths
source_if_exists /usr/share/fzf/key-bindings.zsh
source_if_exists /usr/share/fzf/completion.zsh

export FZF_TMUX_OPTS="-p80%,60%"
export FZF_DEFAULT_COMMAND="fd --type f --hidden --exclude .git"
export FZF_ALT_C_COMMAND="fd --type d --hidden --exclude .git"

export FZF_DEFAULT_OPTS="
--color=bg:#1e1e2e
--color=bg+:#313244
--color=fg:#cdd6f4
--color=header:#f38ba8
--color=hl:#f38ba8
--color=info:#cba6f7
--color=pointer:#f5e0dc
--color=spinner:#f5e0dc
"

export FZF_CTRL_T_OPTS="
--preview 'bat -n --color=always {}'
--bind 'ctrl-/:change-preview-window(down|hidden|)'
"

export FZF_ALT_C_OPTS="
--preview 'tree -C {}'
"

export FZF_CTRL_R_OPTS="
--preview 'echo {}'
--preview-window up:3:hidden:wrap
--bind 'ctrl-/:toggle-preview'
--bind 'ctrl-y:execute-silent(echo -n {2..} | xclip -selection clipboard)+abort'
--color header:italic
--header 'Press CTRL-Y to copy command into clipboard'
"

# ---------------------- #
#         fzf-tab        #
# ---------------------- #
 
zstyle ':completion:*' menu yes select
zstyle ':fzf-tab:*' switch-group ',' '.'
zstyle ':fzf-tab:*' fzf-command fzf
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'lsd --tree --color=always $realpath'

# ---------------------- #
#         zoxide         #
# ---------------------- #

# zoxide
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi

# ---------------------- #
#         volta          #
# ---------------------- #

VOLTA_HOME="/home/dsn/.config/volta"
mkdir -p "$(dirname "$VOLTA_HOME")"
export VOLTA_HOME="$VOLTA_HOME"
export PATH="$VOLTA_HOME/bin:$PATH"
 
# PATH="$PATH:/Users/dsn/.node_modules/bin"
# export npm_config_prefix=~/.node_modules

# ---------------------- #
#         dotnet         #
# ---------------------- #

# export dotnet-ef for migrations
export PATH="$PATH:/users/dsn/.dotnet/tools"

# export for work
export TEMP='/users/dsn/projects/work/repos'
export PATH="/usr/local/share/dotnet:$PATH"

_dotnet_zsh_complete()
{
  local completions=("$(dotnet complete "$words")")

  # If the completion list is empty, just continue with filename selection
  if [ -z "$completions" ]
  then
    _arguments '*::arguments: _normal'
    return
  fi

  # This is not a variable assignment, don't remove spaces!
  _values = "${(ps:\n:)completions}"
}

compdef _dotnet_zsh_complete dotnet

# ---------------------- #
#          accept        #
# ---------------------- #

# ctrl + space to accept
bindkey '^ ' autosuggest-accept
bindkey '^Y' autosuggest-accept

# ---------------------- #
#        extract         #
# ---------------------- #

ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.tar.xz)    tar xJf $1   ;;
      *.bz2)       bunzip3 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# ---------------------- #
#      fn bindings       #
# ---------------------- #

autoload -U edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

run-cd-command () { BUFFER="cd .."; zle accept-line }
zle -N run-cd-command
bindkey '^u' run-cd-command

# ---------------------- #
#      1Password         #
# ---------------------- #

if command -v op &> /dev/null
then
  eval "$(op completion zsh)"; compdef _op op
fi

# ---------------------- #
#         vivid          #
# ---------------------- #

# export LS_COLORS="$(vivid generate catppuccin-mocha)"

# ---------------------- #
#         sesh           #
# ---------------------- #

function sesh-sessions() {
  {
    exec </dev/tty
    exec <&1
    local session
    session=$(sesh list -t -c | fzf --height 40% --reverse --border-label ' sesh ' --border --prompt '⚡  ')
    zle reset-prompt > /dev/null 2>&1 || true
    [[ -z "$session" ]] && return
    sesh connect $session
  }
}

zle     -N             sesh-sessions
bindkey -M vicmd '\es' sesh-sessions
bindkey -M viins '\es' sesh-sessions

# ---------------------- #
#        neovim          #
# ---------------------- #

# ctrl + n to open nvim
function run_nvim() {
  BUFFER="nvim && clear"
  zle accept-line
}
zle -N run_nvim
bindkey "^n" run_nvim

# ---------------------- #
#        lazygit         #
# ---------------------- #

function run_lazy_git() {
  BUFFER="lazygit && clear"
  zle accept-line
}
zle -N run_lazy_git
bindkey "^g" run_lazy_git

# ---------------------- #
#        justfile        #
# ---------------------- #

export JUST_UNSTABLE=1

# ---------------------- #
#        keychain        #
# ---------------------- #

if command -v keychain >/dev/null; then
  eval "$(keychain --eval --quiet id_ed25519)"
fi

# ---------------------- #
#        starship        #
# ---------------------- #

if [[ $TERM != "dumb" ]]; then
  eval "$(starship init zsh)"
fi

# ---------------------- #
#        aliases         #
# ---------------------- #

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias h='cd ~/'
alias cd..='cd ..'
alias cf='cd ~/.config'
alias cfp='cd ~/projects/'
alias cfz='nvim $HOME/dotfiles/zsh/zshrc'
alias cft='nvim $HOME/dotfiles/tmux/config'
alias cfi='nvim $HOME/dotfiles/i3/config'
alias cfg='nvim $HOME/dotfiles/git/config'
alias cfj='nvim $HOME/dotfiles/justfile'
alias cp='cp -v'
alias d='cd ~/dotfiles'
alias df='df -h'
alias mkdir='mkdir -pv'
alias mv='mv -v'
alias rl='source ~/.config/zsh/.zshrc'
alias cat=bat
# alias lpath='echo $PATH | tr '\'':'\'' '\''

# lsd
alias l='lsd -lA --group-dirs=first'
alias la='lsd -A'
alias ll='lsd -l'
alias lla='lsd -lA'
alias lls='lsd -lA --total-size'
alias llt='lsd -l --tree' '\'''
alias lso='lsd -lA --group-dirs=first --permission=octal'
alias lst='lsd -lAt'
alias lt='lsd --tree'
alias ltr='lsd -lA --tree'
alias ls=lsd

# awk
alias awk=nawk

# git
# alias -- churn='!f() { git log --all -M -C --name-only --format='\''format:'\'' "$@" | sort | grep -v '\''^$'\'' | uniq -c | sort | awk '\''BEGIN {print "count    file"} {print $1 "  " $2}'\'' | sort -g; }; f'
alias day='!sh -c '\''git log --reverse --no-merges --branches --date=iso --after="yesterday 23:59" --author="`git config --get user.name`"'\'''
alias delete-merged-branches='!f() { git checkout --quiet master && git branch --merged | grep --invert-match '\''\*'\'' | xargs -n 1 git branch --delete; git checkout --quiet @{-1}; }; f'
alias g="git"
alias ga="git add ."
alias gc="git commit -m"
alias gd="git diff"
alias gpl="git pull"
alias gl="git ls"
alias gp="git push origin master"
alias gpf="git push --force-with-lease"
alias gs="git st"
alias cb="git cb"
alias gam="git commit --amend --no-edit"
alias lzg="lazygit"

# docker
alias di='docker images'
alias drm='docker rm $(docker ps -qa --no-trunc --filter "status=exited")'
alias drmi='docker rmi $(docker images -q -f dangling=true)'
alias ds='docker ps -a'

# du
alias dud='du --max-depth=1 --human-readable'
alias duf='du --summarize --human-readable *'
alias j=just

# npm
# alias -- nd='npm run dev'
# alias -- ni='npm install'
# alias -- nrl='npm run lint'
# alias -- nrt='npm run typecheck'
# alias -- ns='npm start'
# alias -- nt='npm test'
# alias -- ntu='npm run test:update-snapshot'

alias rl='source ~/.config/zsh/.zshrc'

# trash
# alias -- rm=trash-put
# alias -- rmd=trash-put

# sesh
alias s='sesh connect $(sesh list --icons | fzf --ansi)'

# tracert
alias tracert=trip

# alias -g -- CA='2>&1 | cat -A'
# alias -g -- G='| grep'
# alias -g -- H='| head'
# alias -g -- L='| less'
# alias -g -- LL='2>&1 | less'
# alias -g -- M='| most'
# alias -g -- NE='2> /dev/null'
# alias -g -- NUL='> /dev/null 2>&1'
# alias -g -- P='2>&1| pygmentize -l pytb'
# alias -g -- T='| tail'

# source /nix/store/5sz7nq1fa9xm5qmr4bykqcf9cz9b9gkf-zsh-syntax-highlighting-0.8.0/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
# ZSH_HIGHLIGHT_HIGHLIGHTERS+=()
