---
# TODO: add users (dsn and deploy)
# TODO :setup secure ssh (deploy w/ nopass sshkey)
# TODO: sudo for dsn and root access for deploy user
# TODO: maybe simple vim config for users (dsn, deploy and root) ?
- name: Install core
  hosts: all # "{{ hosts }}"
  become: true
  tasks:
    - name: Install core packages
      ansible.builtin.apt:
        name:
          - net-tools
          - nfs-common
          - qemu-guest-agent
          - unzip
        update_cache: true

    - name: Start guest qemu-guest-agent
      ansible.builtin.service:
        name: qemu-guest-agent
        state: started
        enabled: true
