---
# TODO: add users (dsn and deploy)
# TODO :setup secure ssh (deploy w/ nopass sshkey)
# TODO: sudo for dsn and root access for deploy user
# TODO: maybe simple vim config for users (dsn, deploy and root) ?
- name: Install core
  hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: install core packages
      apt:
        name:
          - net-tools
          - nfs-common
          - qemu-guest-agent
          - unzip
        update_cache: yes

    - name: start guest qemu-guest-agent
      service:
        name: qemu-guest-agent
        state: started
        enabled: yes
