{ ... }:
{
  imports = [
    ./auto-upgrade.nix
    ./cifs.nix
    ./i18n.nix
    ./nix.nix
    ./packages.nix
    ./sudo.nix
    ./service-avahi.nix
    ./service-cups.nix
    ./service-docker-registry.nix
    ./service-fail2ban.nix
    ./service-gitea.nix
    ./service-homepage-dashboard.nix
    ./service-jellyfin.nix
    ./service-k3s.nix
    ./service-nginx.nix
    ./service-openssh.nix
    ./service-postgres.nix
    ./service-prometheus.nix
    ./service-traefik.nix
    ./shells.nix
    ./sops.nix
    ./users.nix
    ./virtualisation.nix
    ./zram.nix
  ];
}
