---
- hosts: localhost 
  become: true 
  tasks:

    - name: Tmux | Install build deps 
      package:
        state: present
        name:
          - libncurses5-dev
          - libncursesw5-dev
          - pkg-config
          - libevent-dev
          - bison
          - autotools-dev
          - automake

    - name: Tmux | Get latest release
      uri:
        url: https://api.github.com/repos/tmux/tmux/releases/latest
        return_content: true
      register: json_reponse

    - name: Tmux | Download tarball
      get_url:
        url: "{{ json_reponse.json.tarball_url }}"
        dest: "/tmp/tmux-latest.tar.gz"

    - name: Tmux | Unarchive tarball 
      unarchive: 
        src: "/tmp/tmux-latest.tar.gz"
        dest: "/tmp"
        list_files: yes
      register: tmux_archive_contents

    - name: Tmux | Generate configure 
      shell: 
        chdir: /tmp/{{ tmux_archive_contents.files[0] }}
        cmd: "./autogen.sh"

    - name: Tmux | Run configure 
      become: true
      shell: 
        chdir: /tmp/{{ tmux_archive_contents.files[0] }}
        cmd: "./configure"

    - name: Tmux | Make install 
      shell: 
        chdir: /tmp/{{ tmux_archive_contents.files[0] }}
        cmd: "make && sudo make install"

    - name: Tmux | Remove build dir 
      file: 
        state: absent
        path: "/tmp/{{ tmux_archive_contents.files[0] }}"
        
    - name: Tmux | Remove tarball 
      file: 
        state: absent
        path: "/tmp/tmux-latest.tar.gz"
