# ansible-galaxy collection install ansible.windows
# ansible-galaxy collection install chocolatey.chocolatey

---
- hosts: win
  become: false
  gather_facts: false

  tasks:
    # - name: Upgrade installed packages
    #   chocolatey.chocolatey.win_chocolatey:
    #     name: all
    #     state: latest
    - name: Install packages
      chocolatey.chocolatey.win_chocolatey:
        name:
          - git
          # - microsoft-windows-terminal
          - notepadplusplus
          - nerd-fonts-robotomono
          - nerd-fonts-cascadiacode
          - nerd-fonts-firacode
          # - winrar
        state: present
