---
services:
  grafana:
    image: grafana/grafana-oss:11.0.0
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - frontend
    restart: unless-stopped

networks:
  frontend:
    external: true

volumes:
  grafana-data:
    driver: local
