---
name: Flake Checker
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  flake-checker:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v9
